# Generated by Django 4.2.2 on 2023-06-29 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=512)),
                ('precio_soles', models.FloatField(blank=True, null=True)),
                ('precio_dolares', models.FloatField(blank=True, null=True)),
                ('categoria', models.TextField(max_length=30)),
                ('marca', models.TextField(max_length=20)),
                ('proveedor', models.TextField(max_length=30)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
